name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  template-update:
    runs-on: ubuntu-latest
    steps:
    - name: Get Github Actions
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate new README Stats
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Push new README stats
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push -f
        fi
    - name: Get Github Actions
      uses: actions/checkout@v3
    - name: Generate Waka Stats
      uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
             WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
             GH_TOKEN: ${{ secrets.GH_TOKEN }}
                        
  update-readme:
      runs-on: ubuntu-latest
      needs: template-update
      steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: 'orhanar'
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - name: Get Updated Blog Entries
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://orhanar.github.io/blog/feed.xml"
