name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Actions Checkout
      uses: actions/checkout@v3
    - name: Generate Recent Activity
      uses: Readme-Workflows/recent-activity@v2.3.3
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}   
      with:
          CONFIG_FILE: './.github/workflows/activity.yml'
    - name: Generate Waka Stats
      uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_UPDATED_DATE: "True"
        SHOW_LINES_OF_CODE: "True"
        SHOW_TOTAL_CODE_TIME: "True"
        SHOW_COMMIT: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_PROJECTS: "True"
        SHOW_TIMEZONE: "True"
        SHOW_EDITORS: "True"
        SHOW_LANGUAGE_PER_REPO: "True"
        SHOW_SHORT_INFO: "True"
        SHOW_LOC_CHART: "True"
        LOCALE: "en"   
        
   publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get Github Actions
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate and Push new README Stats
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config --global user.name github-actions[bot]
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git pull origin master
        git push -f origin master
        fi
