name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Waka Stats
      uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
   publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Get Github Actions
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate and Push new README Stats
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push -f
        fi
    - name: Get Actions Checkout
      uses: actions/checkout@v3
    - name: Get Activity Updates
      uses: Readme-Workflows/recent-activity@{version}
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Pull in dev.to posts
      uses: gautamkrishnar/blog-post-workflow@master
      with:
          feed_list: "https://orhanar.github.io/blog/feed.xml"
