name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
  
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Waka Stats
      uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
  
  
  
