name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
    
jobs:
  waka-update:
    runs-on: ubuntu-latest
    steps:
     - name: Get Github Actions
       uses: actions/checkout@v3
     - name: Generate Waka Stats
       uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
       with:
             WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
             GH_TOKEN: ${{ secrets.GH_TOKEN }}
  readme-update: 
    runs-on: ubuntu-latest
    needs: waka-update
    steps:    
      - name: Get Github Actions
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Generate new README Stats
        uses: teoxoy/profile-readme-stats@v1
        with:
         token: ${{ secrets.GH_TOKEN }}                 
  events-update:
    runs-on: ubuntu-latest
    needs: readme-update
    steps:
    - name: Get Github Actions
      uses: actions/checkout@v3
    - name: Generate dynamic stats
      uses: Readme-Workflows/recent-activity@main
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          CONFIG_FILE: "./.github/update-readme.config.yml"
  blog-update:
    runs-on: ubuntu-latest
    needs: events-update
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Updated Blog Entries
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://orhanar.github.io/blog/feed.xml" 
  readme-push: 
    runs-on: ubuntu-latest
    needs: blog-update
    steps:
      - name: Get Github Actions
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: "master" 
      - name: Push new README stats
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update README"
          git push -f
          fi
 
  
