name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
    
jobs:
  waka-update:
    runs-on: ubuntu-latest
    steps:
     - name: Get Github Actions
       uses: actions/checkout@v3
     - name: Generate Waka Stats
       uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
       with:
             WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
             GH_TOKEN: ${{ secrets.GH_TOKEN }}    
  events-update:
    runs-on: ubuntu-latest
    needs: waka-update
    steps:
    - name: Get Github Actions
      uses: actions/checkout@v2.3.4
    - name: Generate dynamic stats
      uses: Readme-Workflows/recent-activity@{version}
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          CONFIG_FILE: "./.github/update-readme.config.yml" 
