name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
    
jobs:
  events-update:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  blog-update:
    runs-on: ubuntu-latest
    needs: events-update
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://orhanar.github.io/blog/feed.xml" 
