name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
    
jobs:
  readme-update: 
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Generate README.md
       uses: teoxoy/profile-readme-stats@v2
       with:
        token: ${{ secrets.GH_TOKEN }}
     - name: Update README.md
       run: |
         if [[ "$(git status --porcelain)" != "" ]]; then
         git config user.name github-actions[bot]
         git config user.email 41898282+github-actions[bot]@users.noreply.github.com
         git add .
         git commit -m "Update README"
         git push
         fi
  waka-update:
    runs-on: ubuntu-latest
    needs: readme-update
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  events-update:
     runs-on: ubuntu-latest
     name: Update Profile README
     steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@{version}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  blog-update:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://orhanar.github.io/blog/feed.xml" 
